export const textColor = {
  gray10: 'text-gray-10',
  gray20: 'text-gray-20',
  gray30: 'text-gray-30',
  gray40: 'text-gray-40',
  gray50: 'text-gray-50',
  gray60: 'text-gray-60',
  gray70: 'text-gray-70',
  gray80: 'text-gray-80',
  gray90: 'text-gray-90',
  gray100: 'text-gray-100',
  gray110: 'text-gray-110',
  gray120: 'text-gray-120',
  white: 'text-white',
  success: 'text-success',
  dangerDefault: 'text-danger-default',
  dangerPress: 'text-danger-press',
  primaryDefault: 'text-primary-default',
  primaryPress: 'text-primary-press',
} as const;
