export const QUERY_KEYS = {
  GET_STUDY_INFO: ['GET_STUDY_INFO'],
  GET_QUIZ_LIST: ['GET_QUIZ_LIST'],
  GET_RANKING_LIST: ['GET_RANKING_LIST'],
  GET_QUIZ_BY_ID: ['GET_QUIZ_BY_ID'],
  GET_QUIZREPLIES_BY_ID: ['GET_QUIZREPLIES_BY_ID'],
  GET_USER_INFO: ['GET_USER_INFO'],
  GET_QUIZREPLY: ['GET_QUIZ_REPLY'],
  GET_SORTED_QUIZREPLY: ['GET_SORTED_QUIZREPLY'],
} as const;
